### ISSUE TITLE
Is this Services works with Ionic2 application?

### ISSUE THREAD

**Issue by vaibsVB** [astronaut1712/angular2-odoo-jsonrpc#1]
I apologies for creating issue to ask a question, I am not able to find how to get in contact with you.

I have just gone through your `angular2-odoo-jsonrpc` repository.
I want to ask that if this `angular2-odoo-jsonrpc` works fine, then can I implement same code (or by doing some changes) i.e. services in `ionic2` application for `Android` and `iOS`.

Because I tried to make ionic2 services (using my own code not yours) to login and make other calls, but its not working and gives `CORS` and `JSONP` error.

Have you tried to make such service for `ionic2 framework`.
I want to run your services to do work in my `ionic2 application.`

Thanks in Advance

**Comment by astronaut1712** [comment]
Hi,

If you want to use cross domain, I think we should configure allow CORS from server side, maybe nginx or odoo server side. If you want to enable CORS from nginx, you can take a look [enable CORS](http://enable-cors.org/server_nginx.html). If you don't use nginx reverse proxy, you can take a look from http://chunniu.sinaapp.com/odoo/reference/http.html.

I tested on allowing CORS but haven't tested on JSONP yet. :)

you can  contact to me at [quang.astronaut@gmail.com](mailto:quang.astronaut@gmail.com) :)

**Comment by vaibsVB** [comment]
Thanks for reply. And sorry for being late.
I will try what suggested by you.
