### ISSUE TITLE
Check the session i valid or not?

### ISSUE THREAD

**Issue by hengkyz** [astronaut1712/angular2-odoo-jsonrpc#6]
i create a login page,
after login i wonder what mechanism that we should use to check whether the session is valid or not, after the user login

**Comment by astronaut1712** [comment]
I think it is from odoo side. Client can't know the session is valid or not. Do you have any idea?

**Comment by hengkyz** [comment]
still exploring the web module from odoo, i will try to combine it with jwt token so i have double validation for the session.
